// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/job.proto

package pb // import "github.com/liujianping/job/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobStatus int32

const (
	JobStatus_UnknownJob         JobStatus = 0
	JobStatus_JobCreated         JobStatus = 1
	JobStatus_JobAccepted        JobStatus = 2
	JobStatus_JobRunning         JobStatus = 3
	JobStatus_JobCanceled        JobStatus = 4
	JobStatus_JobDealineExceeded JobStatus = 5
	JobStatus_JobTimeoutExceeded JobStatus = 6
	JobStatus_JobRetryTerminated JobStatus = 7
	JobStatus_JobCompleted       JobStatus = 8
)

var JobStatus_name = map[int32]string{
	0: "UnknownJob",
	1: "JobCreated",
	2: "JobAccepted",
	3: "JobRunning",
	4: "JobCanceled",
	5: "JobDealineExceeded",
	6: "JobTimeoutExceeded",
	7: "JobRetryTerminated",
	8: "JobCompleted",
}
var JobStatus_value = map[string]int32{
	"UnknownJob":         0,
	"JobCreated":         1,
	"JobAccepted":        2,
	"JobRunning":         3,
	"JobCanceled":        4,
	"JobDealineExceeded": 5,
	"JobTimeoutExceeded": 6,
	"JobRetryTerminated": 7,
	"JobCompleted":       8,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_job_fd9f5eb5c763d461, []int{0}
}
func (x *JobStatus) SetValue(v int32) {
	*x = JobStatus(v)
}
func (x JobStatus) GetValue() int32 {
	return int32(x)
}

type Job struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Command              string            `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Argments             []string          `protobuf:"bytes,4,rep,name=argments,proto3" json:"argments,omitempty"`
	Envs                 map[string]string `protobuf:"bytes,5,rep,name=envs,proto3" json:"envs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Payload              []byte            `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Crontab              string            `protobuf:"bytes,7,opt,name=crontab,proto3" json:"crontab,omitempty"`
	RepeatInterval       string            `protobuf:"bytes,8,opt,name=repeat_interval,proto3" json:"repeat_interval,omitempty"`
	RepeatTimes          int32             `protobuf:"varint,9,opt,name=repeat_times,proto3" json:"repeat_times,omitempty"`
	RetryTimes           int32             `protobuf:"varint,10,opt,name=retry_times,proto3" json:"retry_times,omitempty"`
	CmdTimeout           string            `protobuf:"bytes,11,opt,name=cmd_timeout,proto3" json:"cmd_timeout,omitempty"`
	JobTimeout           string            `protobuf:"bytes,12,opt,name=job_timeout,proto3" json:"job_timeout,omitempty"`
	CreatedAt            int64             `protobuf:"varint,13,opt,name=created_at,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_fd9f5eb5c763d461, []int{0}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Job) GetArgments() []string {
	if m != nil {
		return m.Argments
	}
	return nil
}

func (m *Job) GetEnvs() map[string]string {
	if m != nil {
		return m.Envs
	}
	return nil
}

func (m *Job) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Job) GetCrontab() string {
	if m != nil {
		return m.Crontab
	}
	return ""
}

func (m *Job) GetRepeatInterval() string {
	if m != nil {
		return m.RepeatInterval
	}
	return ""
}

func (m *Job) GetRepeatTimes() int32 {
	if m != nil {
		return m.RepeatTimes
	}
	return 0
}

func (m *Job) GetRetryTimes() int32 {
	if m != nil {
		return m.RetryTimes
	}
	return 0
}

func (m *Job) GetCmdTimeout() string {
	if m != nil {
		return m.CmdTimeout
	}
	return ""
}

func (m *Job) GetJobTimeout() string {
	if m != nil {
		return m.JobTimeout
	}
	return ""
}

func (m *Job) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type JobResult struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResult) Reset()         { *m = JobResult{} }
func (m *JobResult) String() string { return proto.CompactTextString(m) }
func (*JobResult) ProtoMessage()    {}
func (*JobResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_fd9f5eb5c763d461, []int{1}
}
func (m *JobResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResult.Unmarshal(m, b)
}
func (m *JobResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResult.Marshal(b, m, deterministic)
}
func (dst *JobResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResult.Merge(dst, src)
}
func (m *JobResult) XXX_Size() int {
	return xxx_messageInfo_JobResult.Size(m)
}
func (m *JobResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResult.DiscardUnknown(m)
}

var xxx_messageInfo_JobResult proto.InternalMessageInfo

func (m *JobResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *JobResult) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type Report struct {
	Uuid                 string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status               JobStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=job.JobStatus" json:"status,omitempty"`
	Result               *JobResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Timestamp            int64      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_fd9f5eb5c763d461, []int{2}
}
func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (dst *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(dst, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Report) GetStatus() JobStatus {
	if m != nil {
		return m.Status
	}
	return JobStatus_UnknownJob
}

func (m *Report) GetResult() *JobResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Report) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Job)(nil), "job.Job")
	proto.RegisterMapType((map[string]string)(nil), "job.Job.EnvsEntry")
	proto.RegisterType((*JobResult)(nil), "job.JobResult")
	proto.RegisterType((*Report)(nil), "job.Report")
	proto.RegisterEnum("job.JobStatus", JobStatus_name, JobStatus_value)
}

func init() { proto.RegisterFile("pb/job.proto", fileDescriptor_job_fd9f5eb5c763d461) }

var fileDescriptor_job_fd9f5eb5c763d461 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xc1, 0x6e, 0xd4, 0x3c,
	0x10, 0xc7, 0xbf, 0x34, 0xbb, 0x69, 0x33, 0xd9, 0x6f, 0x1b, 0x59, 0xa8, 0xb2, 0x2a, 0xaa, 0x86,
	0x1e, 0x4a, 0xc4, 0x61, 0x2b, 0x95, 0x43, 0x11, 0xb7, 0x52, 0xf6, 0x40, 0x8e, 0xa6, 0x5c, 0xb8,
	0x54, 0x76, 0x32, 0x5a, 0xb2, 0x4d, 0xec, 0xc8, 0x71, 0x16, 0xf6, 0x15, 0x78, 0x21, 0xde, 0x80,
	0xe7, 0x42, 0x76, 0xbc, 0xe1, 0xc2, 0x6d, 0xfe, 0xbf, 0xf9, 0xdb, 0x63, 0x7b, 0xc6, 0xb0, 0xe8,
	0xc4, 0xcd, 0x56, 0x89, 0x55, 0xa7, 0x95, 0x51, 0x24, 0xdc, 0x2a, 0x71, 0xf5, 0x3b, 0x84, 0xb0,
	0x50, 0x82, 0x10, 0x98, 0x0d, 0x43, 0x5d, 0xd1, 0x20, 0x0b, 0xf2, 0x98, 0xb9, 0xd8, 0x32, 0xc9,
	0x5b, 0xa4, 0x47, 0x23, 0xb3, 0x31, 0xa1, 0x70, 0x5c, 0xaa, 0xb6, 0xe5, 0xb2, 0xa2, 0xa1, 0xc3,
	0x07, 0x49, 0xce, 0xe1, 0x84, 0xeb, 0x4d, 0x8b, 0xd2, 0xf4, 0x74, 0x96, 0x85, 0x79, 0xcc, 0x26,
	0x4d, 0xae, 0x61, 0x86, 0x72, 0xd7, 0xd3, 0x79, 0x16, 0xe6, 0xc9, 0x2d, 0x59, 0xd9, 0x43, 0x14,
	0x4a, 0xac, 0xd6, 0x72, 0xd7, 0xaf, 0xa5, 0xd1, 0x7b, 0xe6, 0xf2, 0x76, 0xf7, 0x8e, 0xef, 0x1b,
	0xc5, 0x2b, 0x1a, 0x65, 0x41, 0xbe, 0x60, 0x07, 0xe9, 0xea, 0x6a, 0x25, 0x0d, 0x17, 0xf4, 0xd8,
	0xd7, 0x1d, 0x25, 0x79, 0x0d, 0xa7, 0x1a, 0x3b, 0xe4, 0xe6, 0xa9, 0x96, 0x06, 0xf5, 0x8e, 0x37,
	0xf4, 0xc4, 0x39, 0x96, 0x23, 0xfe, 0xe4, 0x29, 0x79, 0x05, 0x0b, 0x6f, 0x34, 0x75, 0x8b, 0x3d,
	0x8d, 0xb3, 0x20, 0x9f, 0xb3, 0x64, 0x64, 0x8f, 0x16, 0x91, 0x4b, 0x48, 0x34, 0x1a, 0xbd, 0xf7,
	0x0e, 0x70, 0x0e, 0x70, 0x68, 0x32, 0x94, 0x6d, 0xe5, 0xd2, 0x6a, 0x30, 0x34, 0x71, 0x85, 0xa0,
	0x6c, 0xab, 0xc7, 0x91, 0x58, 0xc3, 0x56, 0x89, 0xc9, 0xb0, 0x18, 0x0d, 0x5b, 0x25, 0x0e, 0x86,
	0x0b, 0x80, 0x52, 0x23, 0x37, 0x58, 0x3d, 0x71, 0x43, 0xff, 0xcf, 0x82, 0x3c, 0x64, 0xb1, 0x27,
	0xf7, 0xe6, 0xfc, 0x0e, 0xe2, 0xe9, 0x51, 0x48, 0x0a, 0xe1, 0x33, 0xee, 0x7d, 0x4f, 0x6c, 0x48,
	0x5e, 0xc0, 0x7c, 0xc7, 0x9b, 0xe1, 0xd0, 0x93, 0x51, 0xbc, 0x3f, 0x7a, 0x17, 0x5c, 0xdd, 0x41,
	0x5c, 0x28, 0xc1, 0xb0, 0x1f, 0x1a, 0x63, 0x3b, 0x57, 0xaa, 0x0a, 0xdd, 0xca, 0x39, 0x73, 0x31,
	0x39, 0x83, 0x48, 0x23, 0xef, 0x95, 0xf4, 0x6b, 0xbd, 0xba, 0xfa, 0x19, 0x40, 0xc4, 0xb0, 0x53,
	0xda, 0xfc, 0x73, 0x08, 0xae, 0x21, 0xea, 0x0d, 0x37, 0x43, 0xef, 0x96, 0x2d, 0x6f, 0x97, 0x87,
	0xe6, 0x7d, 0x76, 0x94, 0xf9, 0xac, 0xf5, 0x69, 0x57, 0xdc, 0xcd, 0x45, 0xf2, 0xd7, 0x37, 0x1e,
	0x89, 0xf9, 0x2c, 0x79, 0x09, 0xb1, 0x7b, 0x5c, 0xc3, 0xdb, 0x8e, 0xce, 0xc6, 0xeb, 0x4f, 0xe0,
	0xcd, 0xaf, 0xc0, 0x5d, 0x63, 0xdc, 0x9b, 0x2c, 0x01, 0xbe, 0xc8, 0x67, 0xa9, 0xbe, 0xcb, 0x42,
	0x89, 0xf4, 0x3f, 0xab, 0x0b, 0x25, 0x1e, 0xc6, 0xc7, 0x4a, 0x03, 0x72, 0x0a, 0x49, 0xa1, 0xc4,
	0x7d, 0x59, 0x62, 0x67, 0xc1, 0x91, 0x37, 0xb0, 0x41, 0xca, 0x5a, 0x6e, 0xd2, 0xd0, 0x1b, 0x1e,
	0xb8, 0x2c, 0xb1, 0xc1, 0x2a, 0x9d, 0x91, 0x33, 0x20, 0x85, 0x12, 0x1f, 0x91, 0x37, 0xb5, 0xc4,
	0xf5, 0x8f, 0x12, 0xb1, 0xc2, 0x2a, 0x9d, 0x7b, 0xee, 0x7b, 0x34, 0xf1, 0xc8, 0x73, 0xe6, 0x06,
	0x00, 0x75, 0x5b, 0x4b, 0x57, 0xf9, 0x98, 0xa4, 0xb0, 0xb0, 0x1b, 0xab, 0xb6, 0x6b, 0xd0, 0x92,
	0x93, 0x0f, 0x97, 0x5f, 0x2f, 0x36, 0xb5, 0xf9, 0x36, 0x88, 0x55, 0xa9, 0xda, 0x9b, 0xa6, 0x1e,
	0xb6, 0x35, 0x97, 0x5d, 0x2d, 0x37, 0xf6, 0xc7, 0xdd, 0x74, 0x42, 0x44, 0xee, 0xd7, 0xbd, 0xfd,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x63, 0x16, 0xe8, 0x6a, 0x85, 0x03, 0x00, 0x00,
}
